### ISSUE TITLE
Incorrect usage of static variable

### ISSUE THREAD

**Issue by fiwswe** [dokufreaks/plugin-folded#76] opened 2022-08-28 06:19 UTC
DokuWiki 2022.ß7-31 "Igor", PHP 8.0.22

I am getting this PHP Warning:
`PHP message: PHP Warning:  Undefined property: helper_plugin_folded::$ids_count in /dokuwiki-test/lib/plugins/folded/helper.php on line 26`

Looking at the code in `helper.php` it is trying to use a static object property:
```
    static protected $ids_count = 0;
```
I don't think that such a thing exists.

A working alternative looks like this:
```
class helper_plugin_folded extends DokuWiki_Plugin {
    function getMethods() {
        $result = array();
        $result[] = array(
                'name'   => 'getNextID',
                'desc'   => 'Returns the next folded ID.',
                );
        return $result;
    }

    /**
     * Returns the next folded ID.
     */
    function getNextID() {
        static $ids_count = 0;
        global $ID, $ACT;

        $hash = md5($ID.$ACT);
        $ids_count++;
        $id = 'folded_'.$hash.'_'.$ids_count;
        return $id;
    }
}
```
This actually added incremented numbers starting with 1 to the end of the `$id` and produced no PHP Warnings.

fiwswe

**Comment by emovere** [comment] 2022-09-18 01:36
Your solution works for me (the error occurs only on the 1st page load. After that it vanishes. But the error is reproducible if you delete the dokuwiki cache. The error is gone with your fix.

But I have another error (it occurs as well only on the first page load & if the dokuwiki cache is cleared):

`Warning: Undefined property: syntax_plugin_folded_span::$helper in /lib/plugins/folded/syntax/span.php on line 46`

**Comment by emovere** [comment] 2022-09-18 01:47
Solution to the $helper problem in span.php:

Change:
```
                if ($this->helper === null) {
                    $this->helper = plugin_load('helper', 'folded');
                }


```
To:
```
                if (!isset($this->helper)) {
                    $this->helper = plugin_load('helper', 'folded');
                }

```

**Comment by fiwswe** [comment] 2022-09-18 03:09
@emovere Thanks for testing my fix! I was able to reproduce the additional warning you noticed and confirmed your fix does work.

I have added PR #77 to fix both issues. But as stated in the comment to #77 there may be more issues lurking. Should the check for the `helper` property be pulled up to the start of the method?

**Comment by mikeploeger** [comment] 2022-10-10 20:49
@fiwswe 

> Also I take back my comment about multiple use of the helper property. I misread the code and confused it with the renderer property.

Awesome, everything seems fixed now. If you agree, please closed this issue. 🚀

**Closed** 2022-10-10 22:08 UTC
